name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  id-token: write

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/dataclass-argparser

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Pixi
      uses: prefix-dev/setup-pixi@v0.8.1
      with:
        pixi-version: v0.34.0
        cache: true

    - name: Build PyPI package
      run: pixi run build-pypi

    - name: Publish to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
